name: healthy_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.40+41
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  cupertino_icons: ^1.0.2

  animate_do: ^3.0.2
  animated_digit: ^3.2.3
  app_settings: ^5.0.0
  app_tracking_transparency: ^2.0.4
  audioplayers: ^5.1.0
  bot_toast: ^4.1.3
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.9.0
  cloud_functions: ^4.3.4
  crypto: ^3.0.3
  device_info_plus: ^9.0.3
  dio: ^5.1.1
  easy_date_timeline: ^1.0.4
  equatable: ^2.0.5
  expandable_page_view: ^1.0.17
  firebase_analytics: ^10.8.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  firebase_messaging: ^14.7.10
  firebase_remote_config: ^4.2.4
  flutter_cupertino_datetime_picker: ^3.0.0
  flutter_local_notifications: ^16.3.2
  flutter_native_splash: ^2.3.1
  flutter_svg: ^2.0.4
  font_awesome_flutter: ^10.6.0
  formz: ^0.7.0
  get_it: ^7.6.7
  go_router: ^13.2.0
  google_sign_in: ^6.1.4
  in_app_review: ^2.0.8
  loader_overlay: ^4.0.0
  lottie: ^3.0.0
  mask_text_input_formatter: ^2.5.0
  package_info_plus: ^5.0.1
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  screenshot: ^2.1.0
  share_plus: ^7.2.2
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  sign_in_with_apple: ^5.0.0
  smooth_page_indicator: ^1.1.0
  syncfusion_flutter_charts: ^24.1.46+1
  table_calendar: ^3.1.0
  timezone: ^0.9.2
  url_launcher: ^6.1.12
  wave: ^0.2.2

dependency_overrides:
  intl: ^0.18.0

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  flutter_lints: ^3.0.1
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/animations/
    - assets/audio/
    - assets/images/
    - assets/svg/
    - assets/svg/trophies/
    - assets/json/
