name: healthy_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.9+10
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  cupertino_icons: ^1.0.2

  animate_do: ^3.0.2
  animated_digit: ^3.2.3
  app_settings: ^5.0.0
  audioplayers: ^5.1.0
  bot_toast: ^4.1.3
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.9.0
  cloud_functions: ^4.3.4
  crypto: ^3.0.3
  device_info_plus: ^9.0.3
  dio: ^5.1.1
  easy_date_timeline: ^1.0.4
  equatable: ^2.0.5
  expandable_page_view: ^1.0.17
  firebase_analytics: ^10.4.5
  firebase_auth: ^4.7.0
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.3.4
  firebase_messaging: ^14.7.10
  firebase_remote_config: ^4.2.4
  flutter_cupertino_datetime_picker: ^3.0.0
  # flutter_custom_clippers: ^2.1.0
  flutter_local_notifications: ^16.3.1+1
  flutter_native_splash: ^2.3.1
  # flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.4
  font_awesome_flutter: ^10.6.0
  formz: ^0.4.1
  get_it: ^7.2.0
  go_router: ^10.1.0
  # google_maps_flutter: ^2.2.5
  google_sign_in: ^6.1.4
  loader_overlay: ^2.3.2
  lottie: ^2.2.0
  mask_text_input_formatter: ^2.5.0
  package_info_plus: ^4.1.0
  # qr_flutter: ^4.1.0
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  sign_in_with_apple: ^5.0.0
  # smooth_page_indicator: ^1.1.0
  syncfusion_flutter_charts: ^24.1.46+1
  syncfusion_flutter_datepicker: ^24.1.46
  url_launcher: ^6.1.12
  wave: ^0.2.2

dependency_overrides:
  intl: ^0.18.0

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  flutter_lints: ^2.0.1
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/animations/
    - assets/audio/
    - assets/images/
    - assets/json/
